name: Infrastructure Layer 1 (Network, ECR)

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./infrastructure/layer1
      run: terraform init -backend-config="bucket=hcl-project-tf-state-20260219115130774700000001" -backend-config="dynamodb_table=hcl-project-tf-locks" -backend-config="region=us-east-1" -backend-config="key=hcl-project/layer1/terraform.tfstate"

    - name: Terraform Action
      working-directory: ./infrastructure/layer1
      run: terraform ${{ github.event.inputs.action }} -auto-approve
